src/Entity/Agence.php
<?php

namespace App\Entity;

use App\Repository\AgenceRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Serializer\SerializerInterface;
use Symfony\Component\Serializer\Encoder\JsonEncoder;
use Symfony\Component\Serializer\Normalizer\AbstractNormalizer;
use App\Controller\Serializer;
use Symfony\Component\Serializer\Annotation\Groups;

#[ORM\Entity(repositoryClass: AgenceRepository::class)]
class Agence
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    #[Groups("User")]
    private ?string $Name = null;

    #[ORM\Column(length: 255)]
    #[Groups("User")]
    private ?string $photo = null;

    #[ORM\Column(length: 255)]
    private ?string $Description = null;

    #[ORM\OneToMany(mappedBy: 'AgencyName', targetEntity: User::class)]
    private Collection $ClientId;



    public function __construct()
    {
        $this->ClientId = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->Name;
    }

    public function setName(string $Name): self
    {
        $this->Name = $Name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(string $Description): self
    {
        $this->Description = $Description;

        return $this;
    }

    /**
     * @return Collection<int, User>
     */
    public function getClientId(): Collection
    {
        return $this->ClientId;
    }

    public function addClientId(User $clientId): self
    {
        if (!$this->ClientId->contains($clientId)) {
            $this->ClientId->add($clientId);
            $clientId->setAgencyName($this);
        }

        return $this;
    }

    public function removeClientId(User $clientId): self
    {
        if ($this->ClientId->removeElement($clientId)) {
            // set the owning side to null (unless already changed)
            if ($clientId->getAgencyName() === $this) {
                $clientId->setAgencyName(null);
            }
        }

        return $this;
    }
    public function getPhoto(): ?string
    {
        return $this->photo;
    }

    public function setPhoto(string $photo): self
    {
        $this->photo = $photo;

        return $this;
    }
}

src/Form/CompteType.php
<?php

namespace App\Form;

use App\Entity\Compte;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Validator\Constraints\File;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;


class CompteType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('idType') 
            ->add('idUser')
            ->add('cinS1', FileType::class, [               
                'mapped' => false,
                'required' => true,
                'constraints' => [
                    new File([
                        'maxSize' => '1024k',
                        'mimeTypes' => [
                            'image/jpg',
                            'image/jpeg',
                            'image/png',
                        ],
                        'mimeTypesMessage' => 'Inserer une image validee',
                    ])
                ],             
             ])       
            ->add('cinS2', FileType::class, [
               
                'mapped' => false,
                'required' => true,
                'constraints' => [
                    new File([
                        'maxSize' => '1024k',
                        'mimeTypes' => [
                            'image/jpg',
                            'image/jpeg',
                            'image/png',
                        ],
                        'mimeTypesMessage' => 'Inserer une image validee',
                    ])
                ],             
            ])     
            ->add('otherDoc', FileType::class, [
               
                'mapped' => false,
                'required' => true,
                'constraints' => [
                    new File([
                        'maxSize' => '1024k',
                        'mimeTypes' => [
                            'image/jpg',
                            'image/jpeg',
                            'image/png',
                        ],
                        'mimeTypesMessage' => 'Inserer une image validee',
                    ])
                ],             
            ])
            ->add('maxSolde')
            ->add('minSolde')
            ->add('redSolde')
            ->add('save',SubmitType::class)
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Compte::class,
        ]);
    }
}

src/Controller/CompteController.php
<?php

namespace App\Controller;

use App\Entity\Compte;
use App\Entity\TypeCompte;
use App\Form\CompteType;
use App\Form\CompteSearchType;
use App\Repository\CompteRepository;
use App\Repository\TypeCompteRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\File\Exception\FileException;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\String\Slugger\SluggerInterface;
use CMEN\GoogleChartsBundle\GoogleCharts\Charts\PieChart;
use CMEN\GoogleChartsBundle\GoogleCharts\Options\PieChart\PieSlice;
use CMEN\GoogleChartsBundle\GoogleCharts\Charts\BarChart;


#[Route('/compte')]
class CompteController extends AbstractController
{

    #[Route('/statistiques', name: 'app_compte_statistiques', methods: ['POST','GET'])]
    public function statistiques(Request $request ,CompteRepository $compteRepository ,TypeCompteRepository $typeCompteRepository): Response
    {       
            $compte = new Compte();    
            $comptes = []; 
                $comptes = $compteRepository->getStat();
                $prods = array (array("Type compte","Nombre de demandes de COMPTE"));
               $i = 1;
               foreach ($comptes as $prod){
                   $prods[$i] = array($prod["type"],$prod["nbre"]);
                   $i= $i + 1;
               }   
               $bar = new Barchart();
               $pieChart = new Piechart();
               $bar->getData()->setArrayToDataTable($prods);
               $pieChart->getData()->setArrayToDataTable($prods);

               $bar->getOptions()->setTitle('Statistique de nombre de Demandes de compte par Types');
               $bar->getOptions()->getHAxis()->setTitle('Statistique de nombre de Demandes de compte par Types');
               $bar->getOptions() ->getTitleTextStyle()->setColor('#CF0000');
               $bar->getOptions()->getHAxis()->setMinValue(0);
               $bar->getOptions()->setWidth(900);
               $bar->getOptions()->setHeight(500);
   
               $pieChart->getOptions()->setTitle('Statistique de nombre de Demandes par Types');
               $pieChart->getOptions()->setHeight(400);
               $pieChart->getOptions()->setWidth(400);
               $pieChart->getOptions() ->getTitleTextStyle()->setColor('#CF0000');
               $pieChart->getOptions()->getTitleTextStyle()->setFontSize(25);
                
           return $this->render('compte/comptes_chart.html.twig', [
               'bar' => $bar,
               'pieChart' => $pieChart,
   
           ]);
    }
    
    #[Route('/search', name: 'ajax_search', methods: ['GET'])]
    public function searchAction(Request $request, CompteRepository $charityDemandRepository): Response
    {
        $em = $this->getDoctrine()->getManager();

        $requestString = $request->get('q');

        $charitydemands = $em->getRepository('App\Entity\Compte')->findEntitiesByString($requestString);

        if (!$charitydemands) {
            $result['charity_demands']['error'] = "NOT FOUND";
        } else {
            $result['charity_demands'] = $this->getRealEntities($charitydemands);
        }

        return new Response(json_encode($result));
    }

    public function getRealEntities($charitydemands)
    {

        foreach ($charitydemands as $charitydemand) {
            $realEntities[$charitydemand->getId()] = $charitydemand->getStatue();
        }
        return $realEntities;
    }
    #[Route('/view', name: 'app_charity_demand_View', methods: ['GET', 'POST'])]
    public function View(CompteRepository $charityDemandRepository,  Request $request): Response
    {
        $charitydemands = $charityDemandRepository->findAll();
        $form = $this->createForm(CompteSearchType::class);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $searchquery = $form->getData()['statue'];
            $charitydemands = $charityDemandRepository->search($searchquery);
        }
        return $this->render('compte/search.html.twig', [
            'charity_demands' => $charitydemands,
            'form' => $form->createView()
        ]);
    }

    // #[Route('/view', name: 'app_charity_demand_View', methods: ['GET', 'POST'])]
    // public function View(CompteRepository $charityDemandRepository,  Request $request): Response
    // {
    //     $charitydemands = $charityDemandRepository->findAll();
    //     $form = $this->createForm(DemandSearchType::class);
    //     $form->handleRequest($request);

    //     if ($form->isSubmitted() && $form->isValid()) {
    //         $searchquery = $form->getData()['statue'];
    //         $charitydemands = $charityDemandRepository->search($searchquery);
    //     }
    //     return $this->render('compte/accountDeposit_Ad.html.twig', [
    //         'comptes' => $charitydemands,
    //         'form' => $form->createView()
    //     ]);
    // }
    
   /****USER****/   

    #[Route('/createAccount', name: 'compte_create', methods: ['GET', 'POST'])]
    public function new(Request $request, CompteRepository $compteRepository,SluggerInterface $slugger): Response
    {
        $compte = new Compte();        
        $dateCreation= new \DateTime('now');
        $dateFermeture=new \DateTime('now');
        $compte->setDateCreation($dateCreation);
        $compte->setDateFermeture($dateFermeture);
        $form = $this->createForm(CompteType::class, $compte);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $image1 = $form->get('cinS1')->getData();
            $image2 = $form->get('cinS2')->getData();
            $image3 = $form->get('otherDoc')->getData();
            if ($image1) {
                $originalFilename = pathinfo($image1->getClientOriginalName(), PATHINFO_FILENAME);
                $safeFilename = $slugger->slug($originalFilename);
                $newFilename = $safeFilename.'.'.$image1->guessExtension();
                try {
                    $image1->move(
                        $this->getParameter('brochures_directory1'),
                        $newFilename
                    );
                } catch (FileException $e) {
                
                }
              $compte->setCinS1($newFilename);
            }            
            if ($image2) {
                $originalFilename = pathinfo($image2->getClientOriginalName(), PATHINFO_FILENAME);
                $safeFilename = $slugger->slug($originalFilename);
                $newFilename = $safeFilename.'.'.$image2->guessExtension();
                try {
                    $image2->move(
                        $this->getParameter('brochures_directory1'),
                        $newFilename
                    );
                } catch (FileException $e) {
                
                }
              $compte->setCinS2($newFilename);
            }
            if ($image3) {
                $originalFilename = pathinfo($image3->getClientOriginalName(), PATHINFO_FILENAME);
                $safeFilename = $slugger->slug($originalFilename);
                $newFilename = $safeFilename.'.'.$image3->guessExtension();
                try {
                    $image3->move(
                        $this->getParameter('brochures_directory1'),
                        $newFilename
                    );
                } catch (FileException $e) {
                
                }
              $compte->setOtherDoc($newFilename);
             
            }
            $compte->setRib("in progress...");   
            $compte->setSolde("in progress...");
            $compte->setStatue("in progress");
            $compteRepository->save($compte, true);

            return $this->redirectToRoute('All_comptes', [], Response::HTTP_SEE_OTHER);
        }
        
        return $this->renderForm('compte/create.html.twig', [
            'compte' => $compte,   
            'form' => $form,
        ]);
    }

    #[Route('/allCompteFiltre', name: 'allcompteFiltre')]
    public function list(Request $request, CompteRepository $compteRepository)
    {
        $type = $request->query->get('type');
        
        if ($type == 'all') {
            $comptes = $compteRepository->findAll();
        } else {
            $comptes = $compteRepository->findByType($type);
        }
    
        $typecompte = $this->getDoctrine()
            ->getRepository(TypeCompte::class)
            ->findAll();
    
        return $this->render('compte/index.html.twig', [
            'comptes' => $comptes,
            'typecompte' => $typecompte
        ]);
    }
    
    #[Route('/compte_all', name: 'All_comptes')]
    public function index(CompteRepository $compteRepository, TypeCompteRepository $typeRepository ): Response
    {
        $typecompte= $typeRepository->findAll();
        return $this->render('compte/index.html.twig', [
            'comptes' => $compteRepository->findAll(),
            'typecompte' => $typecompte,
        ]);
    }

    #[Route('/details/{id}', name: 'compte_details', methods: ['GET'])]
    public function show(Compte $compte): Response
    {
        return $this->render('compte/details.html.twig', [
            'compte' => $compte,
        ]);
    }
    

    #[Route('/delete/{id}', name: 'app_compte_delete', methods: ['POST'])]
    public function deleteDU(Request $request, Compte $compte, CompteRepository $compteRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$compte->getId(), $request->request->get('_token'))) {
            $compteRepository->remove($compte, true);
        }

        return $this->redirectToRoute('All_comptes', [], Response::HTTP_SEE_OTHER);
    }
    /***********Admin*******/ 


    #[Route('/account_Deposit', name: 'all_deposits')]

templates/compte/_delete_form.html.twig
<form method="post" action="{{ path('app_compte_delete', {'id': compte.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ compte.id) }}">
    <button class="btn">Delete</button>
</form>

templates/compte/_form.html.twig
{{form_start(form,{'attr':{'novalidate':'novalidate'}})}}
                    <div class="card text-white bg-black col-sm-6 col-lg-12  " >
                      <div class="card-header"><h2> Account Information <b class="text-danger">***</b></h2></div>
                    </div>                  
                    <div class="row">
                      <div class="col-md-6">
                        <div class="form-group mb-3 mt-3">
                               {{form_label(form.idType,'Account Type : ',{'attr':{'class':'form-label'}})}}
                            {{ form_widget(form.idType, { 'attr': { 'class': 'form-select' } }) }}  
                        </div>
                      </div>
                        <div class="col-md-6">
                        <div class="form-group mb-3 mt-3">
                               {{form_label(form.idUser,'User : ',{'attr':{'class':'form-label'}})}}
                               {{form_widget(form.idUser ,{'attr':{'class':'form-select'}} ) }}         
                              {# <input type="text"    class="form-control" value="{{type}}" />    #}
                        </div>
                      </div>
                   </div>
                   
                     <div class="row">
                      <div class="col-md-4">
                        <div class="form-group mb-3 mt-3">
                                {{form_label(form.maxSolde,'Max Amount: ',{'attr':{'class':'form-label'}})}}
                                {{form_widget(form.maxSolde,{'attr':{'class':'form-control'}})}} 
                               
                        </div>
                      </div>
                      <div class="col-md-4">
                        <div class="form-group mb-3 mt-3">
                                {{form_label(form.minSolde,'Min Amount : ',{'attr':{'class':'form-label'}})}}
                                {{form_widget(form.minSolde,{'attr':{'class':'form-control'}})}}                
                            
                        </div>
                      </div>
                      <div class="col-md-4">
                        <div class="form-group mb-3 mt-3">
                                {{form_label(form.redSolde,'Red Amount: ',{'attr':{'class':'form-label'}})}}
                                {{form_widget(form.redSolde,{'attr':{'class':'form-control'}})}} 
                        </div>
                      </div>
                    </div>          
                   <div class="card text-white bg-black col-sm-6 col-lg-12  " >
                      <div class="card-header"><h2> 3. Request Documents  <b class="text-danger">***</b></h2></div>
                    </div>                    
                    <div class="row">
                       <label class=" col-md-12 mb-3 mt-4 form-label text-danger"><h3> You should copy your CIN card on both sides and if you have another document, 
                       do not hesitate to add it to reinforce the acceptance of your request </h3></label>
                     <div class="col-md-4">
                        <div class="form-group mb-3 mt-2">                
                                {{form_label(form.cinS1,'First side: ',{'attr':{'class':'form-label'}})}}
                                {{form_widget(form.cinS1,{'attr':{'class':'form-control'}})}}                                 
					              </div>
                      
                     </div>
                     <div class="col-md-4">
                        <div class="form-group mb-3 mt-2">
                                {{form_label(form.cinS2,'Second side: ',{'attr':{'class':'form-label'}})}}
                                {{form_widget(form.cinS2,{'attr':{'class':'form-control'}})}}  
                        </div>                      
                     </div>
                     <div class="col-md-3">
                        <div class="form-group mb-3 mt-2">
                                {{form_label(form.otherDoc,'Other : ',{'attr':{'class':'form-label'}})}}
                                {{form_widget(form.otherDoc,{'attr':{'class':'form-control'}})}}  
                        </div>                      
                     </div>
                    </div>
                    <div class="row">
                       <div class="col-md-6" ></div>
                        <div class="col-md-3 bg-light" >
                         {# <button type="Resset" class="btn btn-primary w-100">
                          Resset
                         </button> #}
                       </div>
                       <div class="col-md-3 bg-light" >
                        {{form_widget(form.save,{'attr':{'class':'btn btn-success w-100'}})}}
                       </div>
                    </div>
                  </div>
 {{form_end(form)}}

templates/compte/accountDeposit_Ad.html.twig
{% extends 'baseAdmin.html.twig' %}

{% block body %}
    
<div class="page-wrapper">
    <div class="container-fluid" id="container-wrapper">
       <div class="card">
	       <div class="d-sm-flex align-items-center justify-content-between">
	          <h5 class=" mb-0 text-gray-800 pl-3">Accounts Demands</h5>
	           <ol class="breadcrumb">               
                 	{# <form action="{{ path('app_produit_rechercher')}}" class="row"> #}

                     <div class="row input-group custom-search-form">
                        <input type="text" id="search" class="form-control" placeholder="Search for a product ..." id="myInput" >
                     </div>
	                 <br>
	             
					   {# <input type="text" class="col form-control mr-3"placeholder="Search a account">
															
						<button type="submit" class="btn btn-primary mr-3"><i class="fa fa-search"></i></button> 
					</form>#}
	          </ol>
	       </div>
       </div>

       <div class="row mt-3">
       <div class="col-lg-12"> 
            <div class="card mb-4">
	             <div class="table-responsive p-3">
		            <div id="geniustable_wrapper" class="dataTables_wrapper dt-bootstrap4 no-footer">
                        <div class="row btn-area"><div class="col-sm-4">
                            <div class="dataTables_length" id="geniustable_length">
                                <label>Show 
                                 <select name="geniustable_length" aria-controls="geniustable" class="custom-select custom-select-sm form-control form-control-sm">
                                    <option value="10">10</option><option value="25">25</option><option value="50">50</option><option value="100">100</option>
                                 </select> 
                                 entries
                                </label>
                            </div>
                         </div>                        
                        </div>
                        <div class="row">
                            <div class="col-sm-12">
                                <table id="geniustable" class="table table-hover dt-responsive dataTable no-footer dtr-inline" cellspacing="0" width="100%" role="grid" aria-describedby="geniustable_info" style="width: 100%;" id="mytable">
		                           <thead class="thead-light">
			                           <tr role="row">
                                            <th class="sorting_disabled" rowspan="1" colspan="1" style="width: 190px;">Account Type</th>
                                            <th class="sorting_disabled" rowspan="1" colspan="1" style="width: 185px;">Date Demands</th>
                                            <th class="sorting_disabled" rowspan="1" colspan="1" style="width: 173px;">Client</th>      
                                            <th class="sorting_disabled" rowspan="1" colspan="1" style="width: 173px;">Statue</th>                                   
                                            <th class="sorting_disabled" rowspan="1" colspan="1" style="width: 173px;">Options</th>
                                        </tr>
		                           </thead>
                                   <tbody id="myTable">
                                        {% for compte in comptes %}  
                                                              
                                            <tr>
                                                <td>{{ compte.idType  }}</td>
                                                <td>{{ compte.dateCreation|date }}</td>
                                                <td>{{ compte.idUser  }}</td>                                                
                                                {% if  compte.statue == "valide" %}
                                                <td><span class="badge bg-success">{{ compte.statue }}</span></td>
                                                 {% elseif compte.statue == "rejected" %}
                                                <td><span class="badge bg-danger">{{ compte.statue }}</span></td>
                                                {% else %}
                                                <td><span class="badge bg-warning">{{ compte.statue }}</span></td>                          
                                                {% endif %}                                             
                                                <td>
                                                    <a href="{{path('compte_Admin_Show', {'id': compte.id})}}"class="btn btn-info btn-sm px-3"> <i class="fa-sharp fa-regular fa-eye"></i></a>
                                                    {# <a href="" class="btn btn-danger btn-sm px-3"><i class="fa-regular fa-square-minus"></i></a> #}
                                                </td>
                                            </tr>
                                            {% else %}
                                                <tr> <td colspan="6">no Demands found</td></tr>
                                        {% endfor %}
		                            </tbody>
                                </table>
                                <div id="geniustable_processing" class="dataTables_processing card" style="display: none;">
                                    <img src="https://product.geniusocean.com/genius-bank/assets/images/33CiUFaI1641808748.gif">
                                </div>
                            </div>
                        </div>
                        <div class="row">
                           <div class="col-sm-12 col-md-5">
                               <div class="dataTables_info" id="geniustable_info" role="status" aria-live="polite">Showing 1 to 6 of 6 entries</div>
                            </div>
                            <div class="col-sm-12 col-md-7">
                                <div class="dataTables_paginate paging_simple_numbers" id="geniustable_paginate">
                                    <ul class="pagination">
                                        <li class="paginate_button page-item previous disabled" id="geniustable_previous">
                                           <a href="#" aria-controls="geniustable" data-dt-idx="0" tabindex="0" class="page-link">Previous</a>
                                        </li>
                                        <li class="paginate_button page-item active">
                                           <a href="#" aria-controls="geniustable" data-dt-idx="1" tabindex="0" class="page-link">1</a>
                                        </li>
                                        <li class="paginate_button page-item next disabled" id="geniustable_next">
                                           <a href="#" aria-controls="geniustable" data-dt-idx="2" tabindex="0" class="page-link">Next</a>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
	            </div>
                
 <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script>
        $(document).ready(function () {
$("#myInput").on("keyup", function () {
var value = $(this).val().toLowerCase();
$("#myTable tr").filter(function () {
$(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
});
});
});
    </script>
	        </div>
        </div>
       </div>
    </div>
</div>
       

{% endblock %}

templates/compte/new.html.twig
{% extends 'baseAdmin.html.twig' %}

{% block body %}


          <!-- Container Fluid-->
          <div class="container-fluid" id="container-wrapper">
            <div class="card">
              <div
                class="d-sm-flex align-items-center py-3 justify-content-between"
              >
                <h5 class="mb-0 text-gray-800 pl-3">
                  Add New Accout Type
                  <a
                    class="btn btn-primary btn-rounded btn-sm"
                    href="https://product.geniusocean.com/genius-bank/admin/page"
                    ><i class="fas fa-arrow-left"></i> Back</a
                  >
                </h5>
                <ol class="breadcrumb py-0 m-0">
                  <li class="breadcrumb-item">
                    <a
                      href="https://product.geniusocean.com/genius-bank/admin/dashboard"
                      >Dashboard</a
                    >
                  </li>
                  <li class="breadcrumb-item">
                    <a href="javascript:;">Request accout</a>
                  </li>
                  <li class="breadcrumb-item">
                    <a
                      href="https://product.geniusocean.com/genius-bank/admin/page"
                      >Accounts/a
                    >
                  </li>
                  <li class="breadcrumb-item">
                    <a
                      href="https://product.geniusocean.com/genius-bank/admin/page/create"
                      >Add New Account</a
                    >
                  </li>
                </ol>
              </div>
            </div>

            <div class="row justify-content-center mt-3">
              <div class="col-md-10">
                <!-- Form Basic -->
              <div class="card mb-4">
                  <div
                    class="card-header py-3 d-flex flex-row align-items-center justify-content-between"
                  >
                    <h6 class="m-0 font-weight-bold text-primary">
                      Add Account Type
                    </h6>
                  </div>

                <div class="card-body">
                    <div
                      class="gocover"
                      style="
                        background: url(https://product.geniusocean.com/genius-bank/assets/images/33CiUFaI1641808748.gif)
                          no-repeat scroll center center rgba(45, 45, 45, 0.5);
                      "
                    ></div>                          
                 {{form_start(form)}}                       

                    <div class="form-group">
                           {{form_label(form.type,'Type : ',{'attr':{'class':'form-label'}})}}
                           {{form_widget(form.type,{'attr':{'class':'form-control'}})}}                
                    </div>

                   <div class="form-group">
                          {{form_label(form.description,'Description : ',{'attr':{'class':'form-label'}})}}
                          {{form_widget(form.description,{'attr':{'class':'form-control'}})}}  
                    </div>
           
                    {{form_widget(form.save,{'attr':{'class':'btn btn-primary w-100'}})}}
           
                 {{form_end(form)}}


                    
                    
                </div>
             </div>

                <!-- Form Sizing -->

                <!-- Horizontal Form -->
              </div>
            </div>
            <!--Row-->
          </div>
          <!---Container Fluid-->
{% endblock %}






{# 
{% block body %}
    <h1>Create new Compte</h1>

    {{ include('compte/_form.html.twig') }}

    <a href="{{ path('app_compte_index') }}">back to list</a>
{% endblock %} #}